### ISSUE TITLE
PHP 7.3 warnings

### ISSUE THREAD

**Issue by henrywright** [haktansuren/handl-utm-grabber#1]
In PHP 7.3 I seem to get hundreds of warnings on each page load. Please see the attached image

![Screenshot 2019-08-12 at 09 26 28](https://user-images.githubusercontent.com/1963288/62853166-659e9300-bce3-11e9-9128-4728b0f94611.png)

**Comment by haktansuren** [comment]
This issue has been officially fixed as of v2.6.4. You can install the latest version of the plugin here https://wordpress.org/plugins/handl-utm-grabber/

**Comment by henrywright** [comment]
Thank you
